package com.google.cloud.bigquery.samples.test;

import com.google.cloud.bigquery.samples.BigqueryUtils;
import com.google.gson.Gson;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;

import java.io.*;
import java.nio.file.Path;
import java.nio.file.Paths;


/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class BigquerySampleTest extends BigqueryUtils {

  protected static class Constants{
    private String projectId;
    private String datasetId;
    private String currentTableId;
    private String newTableId;
    private String cloudStorageInputURI;
    private String cloudStorageOutputURI;
    private String query;
    /**
     * @return the projectId
     */
    public String getProjectId() {
      return projectId;
    }
    /**
     * @return the datasetId
     */
    public String getDatasetId() {
      return datasetId;
    }
    /**
     * @return the currentTableId
     */
    public String getCurrentTableId() {
      return currentTableId;
    }
    /**
     * @return the newTableId
     */
    public String getNewTableId() {
      return newTableId;
    }
    /**
     * @return the query
     */
    public String getQuery() {
      return query;
    }
    /**
     * @return the cloudStorageOutputURI
     */
    public String getCloudStorageOutputURI() {
      return cloudStorageOutputURI;
    }
    /**
     * @return the cloudStorageInputURI
     */
    public String getCloudStorageInputURI() {
      return cloudStorageInputURI;
    }
  }

  protected static Constants CONSTANTS = null ;

  protected BigquerySampleTest() throws JsonSyntaxException, JsonIOException, FileNotFoundException{
    if(CONSTANTS == null){
      InputStream is = this.getClass().getResourceAsStream
              ("/constants.json");
      CONSTANTS = (new Gson()).<Constants>fromJson(
              new InputStreamReader(is),
              Constants.class);
    }
  }



}
