package com.google.cloud.bigquery.samples.test;

import com.google.cloud.bigquery.samples.ExportDataCloudStorageSample;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;

import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.IOException;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class ExportDataCloudStorageSampleTest extends BigquerySampleTest {

  /**
   * @throws JsonSyntaxException
   * @throws JsonIOException
   * @throws FileNotFoundException
   */
  public ExportDataCloudStorageSampleTest() throws JsonSyntaxException, JsonIOException,
      FileNotFoundException {
    super();
  }
  
  @Test
  public void testExportData() throws IOException, InterruptedException{
    ExportDataCloudStorageSample.run(CONSTANTS.getCloudStorageOutputURI(), 
        CONSTANTS.getProjectId(),
        CONSTANTS.getDatasetId(),
        CONSTANTS.getCurrentTableId(),
        5000L);
  }
  
  

}
