package com.google.cloud.bigquery.samples.test;

import static org.junit.Assert.*;

import com.google.api.services.bigquery.model.TableDataInsertAllResponse;
import com.google.cloud.bigquery.samples.StreamingSample;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;
import com.google.gson.stream.JsonReader;

import org.junit.Test;

import java.io.*;
import java.util.Iterator;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class StreamingSampleTest extends BigquerySampleTest {

  /**
   * @throws JsonSyntaxException
   * @throws JsonIOException
   * @throws FileNotFoundException
   */
  public StreamingSampleTest() throws JsonSyntaxException, JsonIOException, FileNotFoundException {
    super();
  }

  @Test
  public void testStream() throws IOException{
    JsonReader json = new JsonReader(
            new InputStreamReader(BigquerySampleTest
                    .class.getResourceAsStream("/streamrows.json")));
    Iterator<TableDataInsertAllResponse> response = StreamingSample.run(
        CONSTANTS.getProjectId(),
        CONSTANTS.getDatasetId(),
        CONSTANTS.getCurrentTableId(),
        json);

    while(response.hasNext()){
      assertTrue(!response.next().isEmpty());
    }

  }

}
