package com.google.cloud.bigquery.samples.test;

import static org.junit.Assert.*;

import com.google.api.services.bigquery.model.TableDataInsertAllResponse;
import com.google.cloud.bigquery.samples.StreamingSample;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;
import com.google.gson.stream.JsonReader;

import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Iterator;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class StreamingSampleTest extends BigquerySampleTest {

  /**
   * @throws JsonSyntaxException
   * @throws JsonIOException
   * @throws FileNotFoundException
   */
  public StreamingSampleTest() throws JsonSyntaxException, JsonIOException, FileNotFoundException {
    super();
  }
  
  @Test
  public void testStream() throws IOException{
    JsonReader json = new JsonReader(
        new FileReader(
            new File(RESOURCE_PATH.resolve("streamrows.json").toString())));
    Iterator<TableDataInsertAllResponse> response = StreamingSample.run(
        CONSTANTS.getProjectId(),
        CONSTANTS.getDatasetId(),
        CONSTANTS.getCurrentTableId(),
        json);
    
    while(response.hasNext()){
      assertTrue(!response.next().isEmpty());
    }
    
  }
  
}
