/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * App Engine target, queue-level settings.
 *
 * The task will be delivered to the App Engine application URL specified by its AppEngineTarget and
 * AppEngineTaskTarget. The documentation for AppEngineTaskTarget explains how the task's host URL
 * is constructed.
 *
 * When creating or updating this type of target, the following scope must be used:
 * `https://www.googleapis.com/auth/cloud-platform`.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppEngineTarget extends com.google.api.client.json.GenericJson {

  /**
   * Overrides for App Engine routing.
   *
   * If set, AppEngineTarget.app_engine_routing_overrides is used for all tasks in the queue, no
   * matter what the setting is for the task-level app_engine_routing.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppEngineRouting appEngineRoutingOverrides;

  /**
   * HTTP request headers.
   *
   * This map contains the header field names and values. Repeated headers are not supported but a
   * header value can contain commas.
   *
   * Some headers, such as the ones below, will be automatically set by Cloud Tasks:
   *
   * * Host: The host is constructed from many settings in   AppEngineTarget and
   * AppEngineTaskTarget. See the   documentation for AppEngineTaskTarget for more   information. If
   * set, the host header has to exactly match the   resolved hostname, otherwise an error will be
   * returned. * Content-Length: This will be computed and overwritten by Cloud Tasks. * X-Google-*:
   * For Google internal use only. * X-AppEngine-*: For Google internal use only. See
   * [here](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-
   * handlers#reading_request_headers).
   *
   * When a task is attempted, AppEngineTarget.headers will be merged with the task's
   * AppEngineTaskTarget.headers and the merged headers will be sent with the task's overrides. In
   * addition, some App Engine headers will be set which contain task-specific information that can
   * be used by the handler; see
   * [here](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-
   * handlers#reading_request_headers).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.String> headers;

  /**
   * Settings that determine the retry behavior.
   *
   * The task's retry configuration (AppEngineTaskTarget.retry_config) overrides the queue's retry
   * configuration (AppEngineTarget.retry_config).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RetryConfig retryConfig;

  /**
   * Settings that determine the throttling behavior.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ThrottleConfig throttleConfig;

  /**
   * Overrides for App Engine routing.
   *
   * If set, AppEngineTarget.app_engine_routing_overrides is used for all tasks in the queue, no
   * matter what the setting is for the task-level app_engine_routing.
   * @return value or {@code null} for none
   */
  public AppEngineRouting getAppEngineRoutingOverrides() {
    return appEngineRoutingOverrides;
  }

  /**
   * Overrides for App Engine routing.
   *
   * If set, AppEngineTarget.app_engine_routing_overrides is used for all tasks in the queue, no
   * matter what the setting is for the task-level app_engine_routing.
   * @param appEngineRoutingOverrides appEngineRoutingOverrides or {@code null} for none
   */
  public AppEngineTarget setAppEngineRoutingOverrides(AppEngineRouting appEngineRoutingOverrides) {
    this.appEngineRoutingOverrides = appEngineRoutingOverrides;
    return this;
  }

  /**
   * HTTP request headers.
   *
   * This map contains the header field names and values. Repeated headers are not supported but a
   * header value can contain commas.
   *
   * Some headers, such as the ones below, will be automatically set by Cloud Tasks:
   *
   * * Host: The host is constructed from many settings in   AppEngineTarget and
   * AppEngineTaskTarget. See the   documentation for AppEngineTaskTarget for more   information. If
   * set, the host header has to exactly match the   resolved hostname, otherwise an error will be
   * returned. * Content-Length: This will be computed and overwritten by Cloud Tasks. * X-Google-*:
   * For Google internal use only. * X-AppEngine-*: For Google internal use only. See
   * [here](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-
   * handlers#reading_request_headers).
   *
   * When a task is attempted, AppEngineTarget.headers will be merged with the task's
   * AppEngineTaskTarget.headers and the merged headers will be sent with the task's overrides. In
   * addition, some App Engine headers will be set which contain task-specific information that can
   * be used by the handler; see
   * [here](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-
   * handlers#reading_request_headers).
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.String> getHeaders() {
    return headers;
  }

  /**
   * HTTP request headers.
   *
   * This map contains the header field names and values. Repeated headers are not supported but a
   * header value can contain commas.
   *
   * Some headers, such as the ones below, will be automatically set by Cloud Tasks:
   *
   * * Host: The host is constructed from many settings in   AppEngineTarget and
   * AppEngineTaskTarget. See the   documentation for AppEngineTaskTarget for more   information. If
   * set, the host header has to exactly match the   resolved hostname, otherwise an error will be
   * returned. * Content-Length: This will be computed and overwritten by Cloud Tasks. * X-Google-*:
   * For Google internal use only. * X-AppEngine-*: For Google internal use only. See
   * [here](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-
   * handlers#reading_request_headers).
   *
   * When a task is attempted, AppEngineTarget.headers will be merged with the task's
   * AppEngineTaskTarget.headers and the merged headers will be sent with the task's overrides. In
   * addition, some App Engine headers will be set which contain task-specific information that can
   * be used by the handler; see
   * [here](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-
   * handlers#reading_request_headers).
   * @param headers headers or {@code null} for none
   */
  public AppEngineTarget setHeaders(java.util.Map<String, java.lang.String> headers) {
    this.headers = headers;
    return this;
  }

  /**
   * Settings that determine the retry behavior.
   *
   * The task's retry configuration (AppEngineTaskTarget.retry_config) overrides the queue's retry
   * configuration (AppEngineTarget.retry_config).
   * @return value or {@code null} for none
   */
  public RetryConfig getRetryConfig() {
    return retryConfig;
  }

  /**
   * Settings that determine the retry behavior.
   *
   * The task's retry configuration (AppEngineTaskTarget.retry_config) overrides the queue's retry
   * configuration (AppEngineTarget.retry_config).
   * @param retryConfig retryConfig or {@code null} for none
   */
  public AppEngineTarget setRetryConfig(RetryConfig retryConfig) {
    this.retryConfig = retryConfig;
    return this;
  }

  /**
   * Settings that determine the throttling behavior.
   * @return value or {@code null} for none
   */
  public ThrottleConfig getThrottleConfig() {
    return throttleConfig;
  }

  /**
   * Settings that determine the throttling behavior.
   * @param throttleConfig throttleConfig or {@code null} for none
   */
  public AppEngineTarget setThrottleConfig(ThrottleConfig throttleConfig) {
    this.throttleConfig = throttleConfig;
    return this;
  }

  @Override
  public AppEngineTarget set(String fieldName, Object value) {
    return (AppEngineTarget) super.set(fieldName, value);
  }

  @Override
  public AppEngineTarget clone() {
    return (AppEngineTarget) super.clone();
  }

}
