/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * App Engine Routing.
 *
 * For more information about services, versions, and instances see [An Overview of App
 * Engine](https://cloud.google.com/appengine/docs/python/an-overview-of-app-engine) and
 * [Microservices Architecture on Google App Engine](https://cloud.google.com/appengine/docs/python
 * /microservices-on-app-engine).
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppEngineRouting extends com.google.api.client.json.GenericJson {

  /**
   * App instance.
   *
   * By default, the task will be sent to an instance which is available when the task is attempted.
   *
   * Requests can only be sent to a specific instance if basic or manual scaling is used. For more
   * information see [here](https://cloud.google.com/appengine/docs/python/an-overview-of-app-
   * engine?hl=en_US#scaling_types_and_instance_classes).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String instance;

  /**
   * App service.
   *
   * By default, the task will be sent to the service which is the default service when the task is
   * attempted ("default").
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String service;

  /**
   * App version.
   *
   * Version names should begin with a letter, to distinguish them from numeric instances in the app
   * URL; for more information see [here](https://cloud.google.com/appengine/docs/python/how-
   * requests-are-routed#soft_routing).
   *
   * By default, the task will be sent to the version which is the default version when the task is
   * attempted ("default").
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String version;

  /**
   * App instance.
   *
   * By default, the task will be sent to an instance which is available when the task is attempted.
   *
   * Requests can only be sent to a specific instance if basic or manual scaling is used. For more
   * information see [here](https://cloud.google.com/appengine/docs/python/an-overview-of-app-
   * engine?hl=en_US#scaling_types_and_instance_classes).
   * @return value or {@code null} for none
   */
  public java.lang.String getInstance() {
    return instance;
  }

  /**
   * App instance.
   *
   * By default, the task will be sent to an instance which is available when the task is attempted.
   *
   * Requests can only be sent to a specific instance if basic or manual scaling is used. For more
   * information see [here](https://cloud.google.com/appengine/docs/python/an-overview-of-app-
   * engine?hl=en_US#scaling_types_and_instance_classes).
   * @param instance instance or {@code null} for none
   */
  public AppEngineRouting setInstance(java.lang.String instance) {
    this.instance = instance;
    return this;
  }

  /**
   * App service.
   *
   * By default, the task will be sent to the service which is the default service when the task is
   * attempted ("default").
   * @return value or {@code null} for none
   */
  public java.lang.String getService() {
    return service;
  }

  /**
   * App service.
   *
   * By default, the task will be sent to the service which is the default service when the task is
   * attempted ("default").
   * @param service service or {@code null} for none
   */
  public AppEngineRouting setService(java.lang.String service) {
    this.service = service;
    return this;
  }

  /**
   * App version.
   *
   * Version names should begin with a letter, to distinguish them from numeric instances in the app
   * URL; for more information see [here](https://cloud.google.com/appengine/docs/python/how-
   * requests-are-routed#soft_routing).
   *
   * By default, the task will be sent to the version which is the default version when the task is
   * attempted ("default").
   * @return value or {@code null} for none
   */
  public java.lang.String getVersion() {
    return version;
  }

  /**
   * App version.
   *
   * Version names should begin with a letter, to distinguish them from numeric instances in the app
   * URL; for more information see [here](https://cloud.google.com/appengine/docs/python/how-
   * requests-are-routed#soft_routing).
   *
   * By default, the task will be sent to the version which is the default version when the task is
   * attempted ("default").
   * @param version version or {@code null} for none
   */
  public AppEngineRouting setVersion(java.lang.String version) {
    this.version = version;
    return this;
  }

  @Override
  public AppEngineRouting set(String fieldName, Object value) {
    return (AppEngineRouting) super.set(fieldName, value);
  }

  @Override
  public AppEngineRouting clone() {
    return (AppEngineRouting) super.clone();
  }

}
