/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * Request message for CloudTasks.CreateTask.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CreateTaskRequest extends com.google.api.client.json.GenericJson {

  /**
   * The response_view specifies which subset of the Task will be returned.
   *
   * By default response_view is Task.View.BASIC; not all information is retrieved by default
   * because some data, such as payloads, might be desirable to return only when needed because of
   * its large size or because of the sensitivity of data that it contains.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String responseView;

  /**
   * Required.
   *
   * The task to add.
   *
   * The user can optionally specify a name for the task in Task.name. Task.name cannot be the same
   * as an existing task. If a name is not specified then the system will generate a random unique
   * name that will be returned in the response as Task.name.
   *
   * If Task.schedule_time is not set or is in the past then Cloud Tasks will set it to the current
   * time.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Task task;

  /**
   * The response_view specifies which subset of the Task will be returned.
   *
   * By default response_view is Task.View.BASIC; not all information is retrieved by default
   * because some data, such as payloads, might be desirable to return only when needed because of
   * its large size or because of the sensitivity of data that it contains.
   * @return value or {@code null} for none
   */
  public java.lang.String getResponseView() {
    return responseView;
  }

  /**
   * The response_view specifies which subset of the Task will be returned.
   *
   * By default response_view is Task.View.BASIC; not all information is retrieved by default
   * because some data, such as payloads, might be desirable to return only when needed because of
   * its large size or because of the sensitivity of data that it contains.
   * @param responseView responseView or {@code null} for none
   */
  public CreateTaskRequest setResponseView(java.lang.String responseView) {
    this.responseView = responseView;
    return this;
  }

  /**
   * Required.
   *
   * The task to add.
   *
   * The user can optionally specify a name for the task in Task.name. Task.name cannot be the same
   * as an existing task. If a name is not specified then the system will generate a random unique
   * name that will be returned in the response as Task.name.
   *
   * If Task.schedule_time is not set or is in the past then Cloud Tasks will set it to the current
   * time.
   * @return value or {@code null} for none
   */
  public Task getTask() {
    return task;
  }

  /**
   * Required.
   *
   * The task to add.
   *
   * The user can optionally specify a name for the task in Task.name. Task.name cannot be the same
   * as an existing task. If a name is not specified then the system will generate a random unique
   * name that will be returned in the response as Task.name.
   *
   * If Task.schedule_time is not set or is in the past then Cloud Tasks will set it to the current
   * time.
   * @param task task or {@code null} for none
   */
  public CreateTaskRequest setTask(Task task) {
    this.task = task;
    return this;
  }

  @Override
  public CreateTaskRequest set(String fieldName, Object value) {
    return (CreateTaskRequest) super.set(fieldName, value);
  }

  @Override
  public CreateTaskRequest clone() {
    return (CreateTaskRequest) super.clone();
  }

}
