/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * A generic empty message that you can re-use to avoid defining duplicated empty messages in your
 * APIs. A typical example is to use it as the request or the response type of an API method. For
 * instance:
 *
 *     service Foo {       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);     }
 *
 * The JSON representation for `Empty` is empty JSON object `{}`.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Empty extends com.google.api.client.json.GenericJson {

  @Override
  public Empty set(String fieldName, Object value) {
    return (Empty) super.set(fieldName, value);
  }

  @Override
  public Empty clone() {
    return (Empty) super.clone();
  }

}
