/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * Pull target, queue-level settings.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PullTarget extends com.google.api.client.json.GenericJson {

  /**
   * The maximum number of attempts for a task.
   *
   * Cloud Tasks will attempt the task `max_attempts` times. If the first attempt fails, then there
   * will be `max_attempts - 1` retries. Must be > 0.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxAttempts;

  /**
   * If true, then the number of attempts is unlimited.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean unlimitedAttempts;

  /**
   * The maximum number of attempts for a task.
   *
   * Cloud Tasks will attempt the task `max_attempts` times. If the first attempt fails, then there
   * will be `max_attempts - 1` retries. Must be > 0.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxAttempts() {
    return maxAttempts;
  }

  /**
   * The maximum number of attempts for a task.
   *
   * Cloud Tasks will attempt the task `max_attempts` times. If the first attempt fails, then there
   * will be `max_attempts - 1` retries. Must be > 0.
   * @param maxAttempts maxAttempts or {@code null} for none
   */
  public PullTarget setMaxAttempts(java.lang.Integer maxAttempts) {
    this.maxAttempts = maxAttempts;
    return this;
  }

  /**
   * If true, then the number of attempts is unlimited.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getUnlimitedAttempts() {
    return unlimitedAttempts;
  }

  /**
   * If true, then the number of attempts is unlimited.
   * @param unlimitedAttempts unlimitedAttempts or {@code null} for none
   */
  public PullTarget setUnlimitedAttempts(java.lang.Boolean unlimitedAttempts) {
    this.unlimitedAttempts = unlimitedAttempts;
    return this;
  }

  @Override
  public PullTarget set(String fieldName, Object value) {
    return (PullTarget) super.set(fieldName, value);
  }

  @Override
  public PullTarget clone() {
    return (PullTarget) super.clone();
  }

}
