/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * A queue is a container of related tasks. Queues are configured to manage how those tasks are
 * dispatched. Configurable properties include rate limits, retry options, target types, and others.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Queue extends com.google.api.client.json.GenericJson {

  /**
   * App Engine queue.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppEngineTarget appEngineTarget;

  /**
   * The queue name. For example: `projects//locations//queues/`
   *
   * * `` must match `[a-zA-Z\\d-:\\.]+` * `` must match `[a-zA-Z\\d-]+`
   *
   * Caller-specified and required in CreateQueueRequest, after which it becomes output only.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Pull queue.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private PullTarget pullTarget;

  /**
   * Output only.
   *
   * The last time this queue was purged.
   *
   * Purge time will be truncated to the nearest microsecond.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String purgeTime;

  /**
   * Output only.
   *
   * The state of the queue.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String queueState;

  /**
   * App Engine queue.
   * @return value or {@code null} for none
   */
  public AppEngineTarget getAppEngineTarget() {
    return appEngineTarget;
  }

  /**
   * App Engine queue.
   * @param appEngineTarget appEngineTarget or {@code null} for none
   */
  public Queue setAppEngineTarget(AppEngineTarget appEngineTarget) {
    this.appEngineTarget = appEngineTarget;
    return this;
  }

  /**
   * The queue name. For example: `projects//locations//queues/`
   *
   * * `` must match `[a-zA-Z\\d-:\\.]+` * `` must match `[a-zA-Z\\d-]+`
   *
   * Caller-specified and required in CreateQueueRequest, after which it becomes output only.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The queue name. For example: `projects//locations//queues/`
   *
   * * `` must match `[a-zA-Z\\d-:\\.]+` * `` must match `[a-zA-Z\\d-]+`
   *
   * Caller-specified and required in CreateQueueRequest, after which it becomes output only.
   * @param name name or {@code null} for none
   */
  public Queue setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Pull queue.
   * @return value or {@code null} for none
   */
  public PullTarget getPullTarget() {
    return pullTarget;
  }

  /**
   * Pull queue.
   * @param pullTarget pullTarget or {@code null} for none
   */
  public Queue setPullTarget(PullTarget pullTarget) {
    this.pullTarget = pullTarget;
    return this;
  }

  /**
   * Output only.
   *
   * The last time this queue was purged.
   *
   * Purge time will be truncated to the nearest microsecond.
   * @return value or {@code null} for none
   */
  public String getPurgeTime() {
    return purgeTime;
  }

  /**
   * Output only.
   *
   * The last time this queue was purged.
   *
   * Purge time will be truncated to the nearest microsecond.
   * @param purgeTime purgeTime or {@code null} for none
   */
  public Queue setPurgeTime(String purgeTime) {
    this.purgeTime = purgeTime;
    return this;
  }

  /**
   * Output only.
   *
   * The state of the queue.
   * @return value or {@code null} for none
   */
  public java.lang.String getQueueState() {
    return queueState;
  }

  /**
   * Output only.
   *
   * The state of the queue.
   * @param queueState queueState or {@code null} for none
   */
  public Queue setQueueState(java.lang.String queueState) {
    this.queueState = queueState;
    return this;
  }

  @Override
  public Queue set(String fieldName, Object value) {
    return (Queue) super.set(fieldName, value);
  }

  @Override
  public Queue clone() {
    return (Queue) super.clone();
  }

}
