/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-08 11:51:56 PST)
 * on 2017-02-08 at 19:52:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudtasks.v2beta2.model;

/**
 * Status of the task.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TaskStatus extends com.google.api.client.json.GenericJson {

  /**
   * Output only.
   *
   * The number of attempts dispatched. This count includes tasks which have been dispatched but
   * haven't received a response.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long attemptDispatchCount;

  /**
   * Output only.
   *
   * The number of attempts which have received a response.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long attemptResponseCount;

  /**
   * Output only.
   *
   * The status of the task's first attempt.
   *
   * Only AttemptStatus.dispatch_time will be set. The other AttemptStatus information is not
   * retained by Cloud Tasks.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AttemptStatus firstAttemptStatus;

  /**
   * Output only.
   *
   * The status of the task's last attempt.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AttemptStatus lastAttemptStatus;

  /**
   * Output only.
   *
   * The number of attempts dispatched. This count includes tasks which have been dispatched but
   * haven't received a response.
   * @return value or {@code null} for none
   */
  public java.lang.Long getAttemptDispatchCount() {
    return attemptDispatchCount;
  }

  /**
   * Output only.
   *
   * The number of attempts dispatched. This count includes tasks which have been dispatched but
   * haven't received a response.
   * @param attemptDispatchCount attemptDispatchCount or {@code null} for none
   */
  public TaskStatus setAttemptDispatchCount(java.lang.Long attemptDispatchCount) {
    this.attemptDispatchCount = attemptDispatchCount;
    return this;
  }

  /**
   * Output only.
   *
   * The number of attempts which have received a response.
   * @return value or {@code null} for none
   */
  public java.lang.Long getAttemptResponseCount() {
    return attemptResponseCount;
  }

  /**
   * Output only.
   *
   * The number of attempts which have received a response.
   * @param attemptResponseCount attemptResponseCount or {@code null} for none
   */
  public TaskStatus setAttemptResponseCount(java.lang.Long attemptResponseCount) {
    this.attemptResponseCount = attemptResponseCount;
    return this;
  }

  /**
   * Output only.
   *
   * The status of the task's first attempt.
   *
   * Only AttemptStatus.dispatch_time will be set. The other AttemptStatus information is not
   * retained by Cloud Tasks.
   * @return value or {@code null} for none
   */
  public AttemptStatus getFirstAttemptStatus() {
    return firstAttemptStatus;
  }

  /**
   * Output only.
   *
   * The status of the task's first attempt.
   *
   * Only AttemptStatus.dispatch_time will be set. The other AttemptStatus information is not
   * retained by Cloud Tasks.
   * @param firstAttemptStatus firstAttemptStatus or {@code null} for none
   */
  public TaskStatus setFirstAttemptStatus(AttemptStatus firstAttemptStatus) {
    this.firstAttemptStatus = firstAttemptStatus;
    return this;
  }

  /**
   * Output only.
   *
   * The status of the task's last attempt.
   * @return value or {@code null} for none
   */
  public AttemptStatus getLastAttemptStatus() {
    return lastAttemptStatus;
  }

  /**
   * Output only.
   *
   * The status of the task's last attempt.
   * @param lastAttemptStatus lastAttemptStatus or {@code null} for none
   */
  public TaskStatus setLastAttemptStatus(AttemptStatus lastAttemptStatus) {
    this.lastAttemptStatus = lastAttemptStatus;
    return this;
  }

  @Override
  public TaskStatus set(String fieldName, Object value) {
    return (TaskStatus) super.set(fieldName, value);
  }

  @Override
  public TaskStatus clone() {
    return (TaskStatus) super.clone();
  }

}
