package com.google.cloud.bigquery.samples;

import com.google.api.services.bigquery.Bigquery;
import com.google.api.services.bigquery.model.Job;
import com.google.api.services.bigquery.model.JobConfiguration;
import com.google.api.services.bigquery.model.JobConfigurationExtract;
import com.google.api.services.bigquery.model.TableReference;

import java.io.IOException;
import java.util.Scanner;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class ExportDataCloudStorageSample extends BigqueryUtils {


 
  // [START main]
  public static void main(String[] args) throws IOException, InterruptedException{
    Scanner scanner = new Scanner(System.in);
    System.out.println("Enter your project id: ");
    String projectId = scanner.nextLine();
    System.out.println("Enter your dataset id: ");
    String datasetId = scanner.nextLine();
    System.out.println("Enter your table id: ");
    String tableId = scanner.nextLine();
    System.out.println("Enter the Google Cloud Storage Path to which you'd like to export: ");
    String cloudStoragePath = scanner.nextLine();
    System.out.println("Enter how often to check if your job is complete (milliseconds): ");
    long interval = scanner.nextLong();
    scanner.close();
    
    run(cloudStoragePath, projectId, datasetId, tableId, interval);
    
  }
  // [END main]
  
  // [START run]
  public static void run( 
      String cloudStoragePath, 
      String projectId, 
      String datasetId, 
      String tableId,
      long interval) throws IOException, InterruptedException{

    Bigquery bigquery = BigqueryServiceFactory.getService();
    
    Job extractJob = extractJob(
        bigquery,
        cloudStoragePath,
        new TableReference()
        .setProjectId(projectId)
        .setDatasetId(datasetId)
        .setTableId(tableId));
    
    Bigquery.Jobs.Get get_job = bigquery.jobs().get(
        extractJob.getJobReference().getProjectId(), 
        extractJob.getJobReference().getJobId());
    
    pollJob(get_job, interval);
    
    System.out.println("Export is Done!");
    
  }
  // [END run]
  
  
  // [START extract_job]
  public static Job extractJob(
      Bigquery bigquery,
      String cloudStoragePath, 
      TableReference table) throws IOException{
    
    JobConfigurationExtract extract = new JobConfigurationExtract()
    .setSourceTable(table)
    .setDestinationUri(cloudStoragePath);

    return bigquery.jobs().insert(table.getProjectId(), 
        new Job().setConfiguration(new JobConfiguration().setExtract(extract)))
        .execute();
  }
  // [END extract_job]

  
  

}
