/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-19 16:23:00 PDT)
 * on 2016-10-19 at 23:23:02 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.language.v1.model;

/**
 * Represents dependency parse tree information for a token.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Cloud Natural Language API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DependencyEdge extends com.google.api.client.json.GenericJson {

  /**
   * Represents the head of this token in the dependency tree. This is the index of the token which
   * has an arc going to this token. The index is the position of the token in the array of tokens
   * returned by the API method. If this token is a root token, then the `head_token_index` is its
   * own index.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer headTokenIndex;

  /**
   * The parse label for the token.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String label;

  /**
   * Represents the head of this token in the dependency tree. This is the index of the token which
   * has an arc going to this token. The index is the position of the token in the array of tokens
   * returned by the API method. If this token is a root token, then the `head_token_index` is its
   * own index.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHeadTokenIndex() {
    return headTokenIndex;
  }

  /**
   * Represents the head of this token in the dependency tree. This is the index of the token which
   * has an arc going to this token. The index is the position of the token in the array of tokens
   * returned by the API method. If this token is a root token, then the `head_token_index` is its
   * own index.
   * @param headTokenIndex headTokenIndex or {@code null} for none
   */
  public DependencyEdge setHeadTokenIndex(java.lang.Integer headTokenIndex) {
    this.headTokenIndex = headTokenIndex;
    return this;
  }

  /**
   * The parse label for the token.
   * @return value or {@code null} for none
   */
  public java.lang.String getLabel() {
    return label;
  }

  /**
   * The parse label for the token.
   * @param label label or {@code null} for none
   */
  public DependencyEdge setLabel(java.lang.String label) {
    this.label = label;
    return this;
  }

  @Override
  public DependencyEdge set(String fieldName, Object value) {
    return (DependencyEdge) super.set(fieldName, value);
  }

  @Override
  public DependencyEdge clone() {
    return (DependencyEdge) super.clone();
  }

}
