/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-19 16:23:00 PDT)
 * on 2016-10-19 at 23:23:02 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.language.v1.model;

/**
 * Represents a phrase in the text that is a known entity, such as a person, an organization, or
 * location. The API associates information, such as salience and mentions, with entities.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Cloud Natural Language API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Entity extends com.google.api.client.json.GenericJson {

  /**
   * The mentions of this entity in the input document. The API currently supports proper noun
   * mentions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<EntityMention> mentions;

  static {
    // hack to force ProGuard to consider EntityMention used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(EntityMention.class);
  }

  /**
   * Metadata associated with the entity.
   *
   * Currently, only Wikipedia URLs are provided, if available. The associated key is
   * "wikipedia_url".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.String> metadata;

  /**
   * The representative name for the entity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The salience score associated with the entity in the [0, 1.0] range.
   *
   * The salience score for an entity provides information about the importance or centrality of
   * that entity to the entire document text. Scores closer to 0 are less salient, while scores
   * closer to 1.0 are highly salient.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float salience;

  /**
   * The entity type.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * The mentions of this entity in the input document. The API currently supports proper noun
   * mentions.
   * @return value or {@code null} for none
   */
  public java.util.List<EntityMention> getMentions() {
    return mentions;
  }

  /**
   * The mentions of this entity in the input document. The API currently supports proper noun
   * mentions.
   * @param mentions mentions or {@code null} for none
   */
  public Entity setMentions(java.util.List<EntityMention> mentions) {
    this.mentions = mentions;
    return this;
  }

  /**
   * Metadata associated with the entity.
   *
   * Currently, only Wikipedia URLs are provided, if available. The associated key is
   * "wikipedia_url".
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.String> getMetadata() {
    return metadata;
  }

  /**
   * Metadata associated with the entity.
   *
   * Currently, only Wikipedia URLs are provided, if available. The associated key is
   * "wikipedia_url".
   * @param metadata metadata or {@code null} for none
   */
  public Entity setMetadata(java.util.Map<String, java.lang.String> metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * The representative name for the entity.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The representative name for the entity.
   * @param name name or {@code null} for none
   */
  public Entity setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * The salience score associated with the entity in the [0, 1.0] range.
   *
   * The salience score for an entity provides information about the importance or centrality of
   * that entity to the entire document text. Scores closer to 0 are less salient, while scores
   * closer to 1.0 are highly salient.
   * @return value or {@code null} for none
   */
  public java.lang.Float getSalience() {
    return salience;
  }

  /**
   * The salience score associated with the entity in the [0, 1.0] range.
   *
   * The salience score for an entity provides information about the importance or centrality of
   * that entity to the entire document text. Scores closer to 0 are less salient, while scores
   * closer to 1.0 are highly salient.
   * @param salience salience or {@code null} for none
   */
  public Entity setSalience(java.lang.Float salience) {
    this.salience = salience;
    return this;
  }

  /**
   * The entity type.
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * The entity type.
   * @param type type or {@code null} for none
   */
  public Entity setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  @Override
  public Entity set(String fieldName, Object value) {
    return (Entity) super.set(fieldName, value);
  }

  @Override
  public Entity clone() {
    return (Entity) super.clone();
  }

}
