/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-19 16:23:00 PDT)
 * on 2016-10-19 at 23:23:02 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.language.v1.model;

/**
 * All available features for sentiment, syntax, and semantic analysis. Setting each one to true
 * will enable that specific analysis for the input.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Cloud Natural Language API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Features extends com.google.api.client.json.GenericJson {

  /**
   * Extract document-level sentiment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean extractDocumentSentiment;

  /**
   * Extract entities.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean extractEntities;

  /**
   * Extract syntax information.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean extractSyntax;

  /**
   * Extract document-level sentiment.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getExtractDocumentSentiment() {
    return extractDocumentSentiment;
  }

  /**
   * Extract document-level sentiment.
   * @param extractDocumentSentiment extractDocumentSentiment or {@code null} for none
   */
  public Features setExtractDocumentSentiment(java.lang.Boolean extractDocumentSentiment) {
    this.extractDocumentSentiment = extractDocumentSentiment;
    return this;
  }

  /**
   * Extract entities.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getExtractEntities() {
    return extractEntities;
  }

  /**
   * Extract entities.
   * @param extractEntities extractEntities or {@code null} for none
   */
  public Features setExtractEntities(java.lang.Boolean extractEntities) {
    this.extractEntities = extractEntities;
    return this;
  }

  /**
   * Extract syntax information.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getExtractSyntax() {
    return extractSyntax;
  }

  /**
   * Extract syntax information.
   * @param extractSyntax extractSyntax or {@code null} for none
   */
  public Features setExtractSyntax(java.lang.Boolean extractSyntax) {
    this.extractSyntax = extractSyntax;
    return this;
  }

  @Override
  public Features set(String fieldName, Object value) {
    return (Features) super.set(fieldName, value);
  }

  @Override
  public Features clone() {
    return (Features) super.clone();
  }

}
