/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package app;

/**
 * Constants class containing word lists for username generation.
 */
public final class WordLists {
  private WordLists() {
  }

  /** List of adjectives for username generation. */
  public static final String[] ADJECTIVES = {
      "Stealthy",
      "Furious",
      "Savage",
      "Shadow",
      "Mystic",
      "Raging",
      "Epic",
      "Silent",
      "Wicked",
      "Legendary",
      "Fiery",
      "Brave",
      "Cunning",
      "Swift",
      "Lone",
      "Dark",
      "Deadly",
      "Fearless",
      "Iron",
      "Crimson",
      "Golden",
      "Silver",
      "Vengeful",
      "Thundering",
      "Frozen",
      "Venomous",
      "Infernal",
      "Glorious",
      "Hidden",
      "Mighty",
      "Proud",
      "Reckless",
      "Stalwart",
      "Fierce",
      "Grim",
      "Bold",
      "Daring",
      "Noble",
      "Heroic",
      "Vicious",
      "Stormy",
      "Merciless",
      "Ghostly",
      "Shifty",
      "Eternal",
      "Arcane",
      "Primordial",
      "Sinister",
      "Radiant",
      "Powerful",
      "Holy",
      "Unholy",
      "Blazing",
      "Ruthless",
      "Jagged",
      "Shattered",
      "Swift",
      "Haunted",
      "Gilded",
      "Crazed",
      "Savage",
      "Ravenous",
      "Lethal",
      "Frosty",
      "Spectral",
      "Divine",
      "Oblivious",
      "Venomous",
      "Twisted",
      "Blighted",
      "Howling",
      "Burning",
      "Enchanted",
      "War-torn",
      "Resilient",
      "Dominant",
      "Immortal",
      "Dire",
      "Relentless",
      "Forsaken",
      "Avenging",
      "Piercing",
      "Brutal",
      "Shimmering",
      "Dauntless",
      "Nightmarish",
      "Ferocious",
      "Infernal"
  };

  /** List of nouns for username generation. */
  public static final String[] NOUNS = {
      "Warrior",
      "Sniper",
      "Assassin",
      "Mage",
      "Knight",
      "Hunter",
      "Rogue",
      "Beast",
      "Dragon",
      "Phantom",
      "Champion",
      "Sorcerer",
      "Guardian",
      "Warlord",
      "Reaper",
      "Shinobi",
      "Valkyrie",
      "Gladiator",
      "Raider",
      "Paladin",
      "Berserker",
      "Ranger",
      "Slayer",
      "Monk",
      "Overlord",
      "Druid",
      "Invoker",
      "Barbarian",
      "Necromancer",
      "Ravager",
      "Demon",
      "Titan",
      "Shadow",
      "Wolf",
      "Leviathan",
      "Viper",
      "Hawk",
      "Phoenix",
      "Tiger",
      "Lion",
      "Serpent",
      "Ghost",
      "Predator",
      "Juggernaut",
      "Crusher",
      "Tyrant",
      "Destroyer",
      "Seer",
      "Summoner",
      "Conqueror",
      "Wanderer",
      "Blight",
      "Tempest",
      "Inferno",
      "Havoc",
      "Specter",
      "Shade",
      "Nightmare",
      "Scourge",
      "Cleric",
      "Lancer",
      "Invoker",
      "Vortex",
      "Anomaly",
      "Havoc",
      "Harbinger",
      "Sentinel",
      "Oracle",
      "Mystic",
      "Vanquisher",
      "Sage",
      "Eclipse",
      "Abyss",
      "Legion",
      "Storm",
      "Fury",
      "Outlaw",
      "Enigma",
      "Reckoning",
      "Executor",
      "Dominion",
      "Omen",
      "Fate",
      "Rift",
      "Chaos",
      "Nemesis",
      "Feral",
      "Inferno",
      "Apex",
      "Ascendant"
  };
}
