/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package genai.imagegeneration;

// [START googlegenaisdk_imggen_raw_reference_with_txt_img]

import com.google.cloud.storage.BlobId;
import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;
import com.google.genai.Client;
import com.google.genai.types.Blob;
import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;
import java.util.Optional;

public class ImageGenRawReferenceWithTextAndImage {

  public static void main(String[] args) {
    // TODO(developer): Replace these variables before running the sample.
    String modelId = "gemini-2.5-flash-image";
    String outputGcsUri = "gs://your-bucket/your-prefix";
    styleTransferCustomization(modelId, outputGcsUri);
  }

  // Generates an image in a new style using style transfer customization with a raw reference image
  // and a text prompt.
  public static Optional<String> styleTransferCustomization(String modelId, String outputGcsUri) {
    // Client Initialization. Once created, it can be reused for multiple requests.
    try (Client client = Client.builder().location("global").vertexAI(true).build()) {

      GenerateContentConfig config =
          GenerateContentConfig.builder().responseModalities("TEXT", "IMAGE").build();

      GenerateContentResponse response =
          client.models.generateContent(
              modelId,
              Content.fromParts(
                  Part.fromUri(
                      "gs://cloud-samples-data/generative-ai/image/teacup-1.png", "image/png"),
                  Part.fromText(
                      "transform the subject in the image so that the teacup is made entirely out of chocolate")),
              config);

      byte[] imageBytes =
          response
              .candidates()
              .flatMap(candidates -> candidates.stream().findFirst())
              .flatMap(Candidate::content)
              .flatMap(Content::parts)
              .flatMap(
                  parts ->
                      parts.stream()
                          .filter(part -> part.inlineData().flatMap(Blob::data).isPresent())
                          .findFirst())
              .flatMap(part -> part.inlineData().flatMap(Blob::data))
              .orElseThrow(() -> new IllegalStateException("No image was generated by the model."));

      Storage storage = StorageOptions.getDefaultInstance().getService();
      String gcsPath = outputGcsUri.replace("gs://", "");
      int slashIdx = gcsPath.indexOf('/');
      String bucket = slashIdx > 0 ? gcsPath.substring(0, slashIdx) : gcsPath;
      String objectName =
          slashIdx > 0
              ? gcsPath.substring(slashIdx + 1) + "/raw_reference.png"
              : "raw_reference.png";
      BlobId blobId = BlobId.of(bucket, objectName);
      BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType("image/png").build();
      storage.create(blobInfo, imageBytes);

      String fullGcsUri = String.format("gs://%s/%s", bucket, objectName);
      System.out.println("Generated image URI: " + fullGcsUri);
      return Optional.of(fullGcsUri);
    }
  }
}
// [END googlegenaisdk_imggen_raw_reference_with_txt_img]
