/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package genai.imagegeneration;

// [START googlegenaisdk_imggen_with_txt]

import com.google.genai.Client;
import com.google.genai.types.Blob;
import com.google.genai.types.Candidate;
import com.google.genai.types.Content;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Image;
import com.google.genai.types.Part;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class ImageGenWithText {

  public static void main(String[] args) throws IOException {
    // TODO(developer): Replace these variables before running the sample.
    String modelId = "gemini-2.5-flash-image";
    String outputFile = "resources/output/dog_newspaper.png";
    generateImage(modelId, outputFile);
  }

  // Generates an image with text input
  public static Image generateImage(String modelId, String outputFile) throws IOException {
    // Client Initialization. Once created, it can be reused for multiple requests.
    try (Client client = Client.builder().location("global").vertexAI(true).build()) {

      GenerateContentConfig config =
          GenerateContentConfig.builder().responseModalities("TEXT", "IMAGE").build();

      GenerateContentResponse response =
          client.models.generateContent(modelId, "A dog reading a newspaper", config);

      byte[] imageBytes =
          response
              .candidates()
              .flatMap(candidates -> candidates.stream().findFirst())
              .flatMap(Candidate::content)
              .flatMap(Content::parts)
              .flatMap(
                  parts ->
                      parts.stream()
                          .filter(part -> part.inlineData().flatMap(Blob::data).isPresent())
                          .findFirst())
              .flatMap(part -> part.inlineData().flatMap(Blob::data))
              .orElseThrow(() -> new IllegalStateException("No image was generated by the model."));

      java.nio.file.Files.write(java.nio.file.Paths.get(outputFile), imageBytes);

      System.out.printf("Created output image using %s bytes\n", imageBytes.length);

      return Image.builder().imageBytes(imageBytes).build();
    }
  }
}
// [END googlegenaisdk_imggen_with_txt]