/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package genai.imagegeneration;

// [START googlegenaisdk_imggen_canny_ctrl_type_with_txt_img]

import com.google.genai.Client;
import com.google.genai.types.ControlReferenceConfig;
import com.google.genai.types.ControlReferenceImage;
import com.google.genai.types.EditImageConfig;
import com.google.genai.types.EditImageResponse;
import com.google.genai.types.GeneratedImage;
import com.google.genai.types.Image;
import java.util.List;
import java.util.Optional;

public class ImageGenCannyCtrlTypeWithTextAndImage {

  public static void main(String[] args) {
    // TODO(developer): Replace these variables before running the sample.
    String modelId = "imagen-3.0-capability-001";
    String outputGcsUri = "gs://your-bucket/your-prefix";
    cannyEdgeCustomization(modelId, outputGcsUri);
  }

  // Generates an image using controlled customization with a Canny Edge image and a text prompt.
  public static Optional<String> cannyEdgeCustomization(String modelId, String outputGcsUri) {
    // Client Initialization. Once created, it can be reused for multiple requests.
    try (Client client = Client.builder().location("global").vertexAI(true).build()) {
      // Create a reference image out of an existing canny edge image signal
      // using https://storage.googleapis.com/cloud-samples-data/generative-ai/image/car_canny.png
      ControlReferenceImage controlReferenceImage =
          ControlReferenceImage.builder()
              .referenceId(1)
              .referenceImage(
                  Image.builder()
                      .gcsUri("gs://cloud-samples-data/generative-ai/image/car_canny.png")
                      .build())
              .config(ControlReferenceConfig.builder().controlType("CONTROL_TYPE_CANNY").build())
              .build();

      // The `[1]` in the prompt refers to the `referenceId` assigned to
      // the control reference image.
      EditImageResponse imageResponse =
          client.models.editImage(
              modelId,
              "a watercolor painting of a red car[1] driving on a road",
              List.of(controlReferenceImage),
              EditImageConfig.builder()
                  .editMode("EDIT_MODE_CONTROLLED_EDITING")
                  .numberOfImages(1)
                  .safetyFilterLevel("BLOCK_MEDIUM_AND_ABOVE")
                  .personGeneration("ALLOW_ADULT")
                  .outputGcsUri(outputGcsUri)
                  .build());

      Image generatedImage =
          imageResponse
              .generatedImages()
              .flatMap(generatedImages -> generatedImages.stream().findFirst())
              .flatMap(GeneratedImage::image)
              .orElseThrow(() -> new IllegalStateException("No image was generated by the model."));

      generatedImage.gcsUri().ifPresent(System.out::println);
      // Example response:
      // gs://your-bucket/your-prefix
      return generatedImage.gcsUri();
    }
  }
}
// [END googlegenaisdk_imggen_canny_ctrl_type_with_txt_img]
